### 创建客户端
POST http://localhost:9091/iam/client/create
Content-Type: application/json

{
  "name": "测试客户端",
  "clientId": "test",
  "clientSecret": "test",
  "accessTokenValidity": null,
  "refreshTokenValidity": null,
  "accessTokenAutoRenewal": null,
  "acceptRepetitionLogin": null
}

### 删除客户端
DELETE http://localhost:9091/iam/client/delete?id=363320030554750976
