### 注册
POST http://localhost:9091/iam/user/register
Content-Type: application/json

{
  "name": "宋志宗",
  "phone": "18888888888",
  "account": "songzhizong",
  "email": "songzhizong@163.com",
  "password": "songzhizong@password"
}

### 查询
POST http://localhost:9091/iam/user/query
Content-Type: application/json

{
  "paging": {
    "pageNumber": 1,
    "pageSize": 10
  },
  "name": "",
  "account": "",
  "email": "",
  "phone": ""
}
