logging:
  config: classpath:logback-spring-dev.xml
spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://127.0.0.1:27011,127.0.0.1:27012,127.0.0.1:27013/zzsong?maxPoolSize=20
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    virtual-host: general
  redis:
    host: 127.0.0.1
    port: 6379

ideal:
  snowflake:
    factory-type: redis
  event:
    broker:
      rabbit:
        enable-local-model: true
