server:
  port: 9091
  shutdown: graceful
spring:
  application:
    name: ZZSONG-IAM
  jackson:
    locale: zh_CN
    time-zone: 'GMT+8'
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
